language: node_js
node_js:
  - 12
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: main
- provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: "CRM-React"
  skip_cleanup: true
  local_dir: public
  region: us-east-2
  on:
    branch: main